### ISSUE TITLE
End-to-end

### ISSUE THREAD

**Issue by Yafaa** [quangnhat185/Plate_detect_and_recognize#10]
![image](https://user-images.githubusercontent.com/62661149/88535883-0d9f9000-d00b-11ea-9644-01bde4e8b016.png)
Everytime i run the findContours function from cv2

**Comment by quangnhat185** [comment]
Hello Yafaa, 

I believe this problem occurred due to inappropriate OpenCV version. I guess are using a version lower than 4.2.0.
You can either try to upgrade your OpenCV or replace the code as:

`cont  = cv2.findContours(binary, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)`

**Comment by Yafaa** [comment]
Hey Yeas i noticed that thanx a lot !

Le lun. 27 juil. 2020 à 18:55, Quang Nguyen <notifications@github.com> a
écrit :
