### ISSUE TITLE
How to train wpod-net.h5 model and create wpod-net.json file?

### ISSUE THREAD

**Issue by iris-mygh** [quangnhat185/Plate_detect_and_recognize#11]
Hi you,
How to train wpod-net.h5 model and create wpod-net.json file?
Please help me to answer the question.
Thank you so much!

**Comment by quangnhat185** [comment]
Hello @lnkngoc,

Wpod-net was originally created and trained by S. M. Silva, and I just simply implement his pre-trained model into real-life application. 

Here, you can refer [his paper](http://sergiomsilva.com/pubs/alpr-unconstrained/) and [github repo](https://github.com/sergiomsilva/alpr-unconstrained).

**Comment by iris-mygh** [comment]
Thanks a lot @quangnhat185
