### ISSUE TITLE
Plate character segmentation with OpenCV error 

### ISSUE THREAD

**Issue by sparshgarg23** [quangnhat185/Plate_detect_and_recognize#2]
Hi,when trying to determine the contours of the license characters,I am getting an error called digit_w and digit_h are undefined.I tried replacing these with the extracted box's width and height.And then the code is working again.

**Comment by quangnhat185** [comment]
Hi @sparshgarg23, thanks for pointing out. I was testing something in another cell and forgot to update. I have updated again and fix the error.

**Comment by sparshgarg23** [comment]
Hi,thanks for getting back.Also ,I was trying to test the model on other car plates.Like japanese.However in those cases,the result comes out to be 0 digits detected.
My assumption is that for japanese plates,we need to fine tune the segmentation and contour procedure right.Let me know if I am on the right track
