### ISSUE TITLE
List out of index error

### ISSUE THREAD

**Issue by wlommusic** [quangnhat185/Plate_detect_and_recognize#20]
![outofindex](https://user-images.githubusercontent.com/64889320/111294485-63937780-8670-11eb-815e-ff3bfaa1542b.png)
having an issue with this code snippet can u pls tell me how to fix this.

**Comment by wlommusic** [comment]
solved.

**Comment by SaiAakash** [comment]
How did you solve it ?

**Comment by wlommusic** [comment]
i made changes some changes to the code

https://github.com/wlommusic/ALPDR
refer from here
