### ISSUE TITLE
[Question] Currently model can be run smoothly on RPi Zero W?

### ISSUE THREAD

**Issue by KennyDizi** [quangnhat185/Plate_detect_and_recognize#3]
Hi Quang, thank you very much for your great work. We a Vietnamese startup company base in HCM City. We're having a smart parking project and our hardware is running on RPi Zero W and use Pi Camera for car detection and license plate recognition.
Let me know if you can give a hand to help project go futher and become a part of project.
Thanks and Best Regards,
Kenny

**Comment by quangnhat185** [comment]
Hello @xamarindevelopervietnam,

It depends on what you define smoothly. If the vehicles stop in a fixed place and wait for some time like in parking area, then it should work. I tested my model on Raspberry Pi 4 and it took around 2 seconds for entire prediction, but I honestly not sure about RPi Zero.  

AI solution might very accurate but requires lots of computational power, so you will need some test and optimization.  I saw your email regarding the project and find it fascinating. And I am glad to be a part of the project, but at the moment I am a bit busy.  

Within this week, I will send you an email so we can discuss further details.

Sincerely,
Quang

**Comment by KennyDizi** [comment]
Hi @quangnhat185 ,
Thank you for your reply!
Both of CPU and DPU are installed Intel NCS2 to boost up the performance. I'm finding Co-founder for this project and very happy if you can give a hand.

Looking forward for you email and let's talk further than.

Best regards,
Kenny
